name: CICD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions@checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.1
      - name: Install dependencies
        run: cd backend && go get .
      - name: build
        run: cd backend && go build -v ./...
